#pragma once

#include "ConstVirtualFunction.hpp"
#include "CosWithTaylorSeries.hpp"
#include "DesignatedInitializer.hpp"
#include "EmptyClass.hpp"
#include "GenericLambda.hpp"
#include "LambdaCapture.hpp"
#include "NonTypeTemplateParameter.hpp"
#include "RangeBasedLoop.hpp"
#include "StaticTypeCheck.hpp"
#include "ThreeComp.hpp"
#include "VoltatileUsage.hpp"
#include "WithoutConstinitSpecifier.hpp"
#include "WithoutRangesExample.hpp"